services:
  quran_player:
    build: .
    container_name: quran_player
    devices:
      - "/dev/snd:/dev/snd"  # Access to the host sound device
    volumes:
      - ./quran:/app/quran  # Mount the directory containing MP3 files
      - ./crontab:/etc/cron.d/mycron  # Map crontab file for easy editing on host
      - /etc/localtime:/etc/localtime:ro  # Sync localtime with the host
      - /dev/snd:/dev/snd  # Map sound device

